# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d03aceced494e4ea4116adb9da1b3f2b7fcb7e5a669b2a828c8e259975245017143504a96f688d34a20ccd6edcb409b2072607e19a4a247b56dbcc9c07d5d595

test:
  secret_key_base: b1bcb68cf818974ab29e710e336ae92a6157c4024e301bd40e717dd9bdd8d74032b37d924e103e35eb9c571617768067cf763f0510bbc687f4936145df6b7f3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
